/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_glub_jni_UID */

#ifndef _Included_com_glub_jni_UID
#define _Included_com_glub_jni_UID
#ifdef __cplusplus
extern "C" {
#endif
#undef com_glub_jni_UID_SUCCESS
#define com_glub_jni_UID_SUCCESS 0L
#undef com_glub_jni_UID_FAILURE
#define com_glub_jni_UID_FAILURE -1L
/*
 * Class:     com_glub_jni_UID
 * Method:    setegid
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_glub_jni_UID_setegid
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_glub_jni_UID
 * Method:    seteuid
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_glub_jni_UID_seteuid
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_glub_jni_UID
 * Method:    setgid
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_glub_jni_UID_setgid
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_glub_jni_UID
 * Method:    setuid
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_glub_jni_UID_setuid
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
